/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PushCouchAppPanel.java
 *
 * Created on 20.02.2011, 17:51:17
 */
package org.pangratz.netbeans.couchapp.actions;

import java.awt.Component;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JDialog;
import javax.swing.JList;
import org.pangratz.netbeans.couchapp.ICouchAppUtil.CouchDbServer;

/**
 *
 * @author clemens
 */
public class PushCouchAppPanel extends javax.swing.JPanel {

    private static class CouchDbServerRenderer extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList jlist, Object o, int i, boolean bln, boolean bln1) {
            if (o != null) {
                CouchDbServer server = (CouchDbServer) o;
                String name = server.getName();
                String url = server.getServer();
                String value = String.format("%s - %s", name, url);
                return super.getListCellRendererComponent(jlist, value, i, bln, bln1);
            }
            return super.getListCellRendererComponent(jlist, o, i, bln, bln1);
        }
    }
    private boolean okPressed = false;
    private final ComboBoxModel couchDbServerModel;
    private final JDialog owner;
    private final LinkedList<CouchDbServer> servers;

    /** Creates new form PushCouchAppPanel */
    public PushCouchAppPanel() {
        this(null, null);
    }

    private ComboBoxModel getCouchDbServerModel() {
        return couchDbServerModel;
    }

    public PushCouchAppPanel(JDialog owner, List<CouchDbServer> servers) {
        super();
        
        this.owner = owner;

        this.servers = new LinkedList<CouchDbServer>();
        if (servers != null) {
            this.servers.addAll(servers);
        }
        couchDbServerModel = new DefaultComboBoxModel(this.servers.toArray());

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choicesButtonGroup = new javax.swing.ButtonGroup();
        predefinedCouchDbInstance = new javax.swing.JRadioButton();
        predefinedCouchDbInstancesComboBox = new javax.swing.JComboBox();
        newCouchDbInstance = new javax.swing.JRadioButton();
        newCouchDbLocationTextField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        choicesButtonGroup.add(predefinedCouchDbInstance);
        predefinedCouchDbInstance.setSelected(true);
        predefinedCouchDbInstance.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.predefinedCouchDbInstance.text")); // NOI18N

        predefinedCouchDbInstancesComboBox.setModel(getCouchDbServerModel());
        predefinedCouchDbInstancesComboBox.setRenderer(new CouchDbServerRenderer());

        choicesButtonGroup.add(newCouchDbInstance);
        newCouchDbInstance.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.newCouchDbInstance.text")); // NOI18N

        newCouchDbLocationTextField.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.newCouchDbLocationTextField.text")); // NOI18N

        messageLabel.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.messageLabel.text")); // NOI18N

        okButton.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(29, 29, 29)
                            .add(predefinedCouchDbInstancesComboBox, 0, 345, Short.MAX_VALUE)
                            .addContainerGap())
                        .add(layout.createSequentialGroup()
                            .add(messageLabel)
                            .addContainerGap())
                        .add(predefinedCouchDbInstance)
                        .add(layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(29, 29, 29)
                                    .add(newCouchDbLocationTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                                .add(newCouchDbInstance))
                            .add(36, 36, 36)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cancelButton)
                        .add(18, 18, 18)
                        .add(okButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(messageLabel)
                .add(18, 18, 18)
                .add(predefinedCouchDbInstance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(predefinedCouchDbInstancesComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(newCouchDbInstance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(newCouchDbLocationTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        okPressed = true;
        owner.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        owner.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.ButtonGroup choicesButtonGroup;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JRadioButton newCouchDbInstance;
    private javax.swing.JTextField newCouchDbLocationTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton predefinedCouchDbInstance;
    private javax.swing.JComboBox predefinedCouchDbInstancesComboBox;
    // End of variables declaration//GEN-END:variables

    public String getChosenCouchDbUrl() {
        if (!okPressed) {
            return null;
        }

        if (predefinedCouchDbInstance.isSelected()) {
            Object selectedItem = predefinedCouchDbInstancesComboBox.getSelectedItem();
            if (selectedItem != null) {
                CouchDbServer server = (CouchDbServer) selectedItem;
                return server.getServer();
            }
        } else if (newCouchDbInstance.isSelected()) {
            return newCouchDbLocationTextField.getText();
        }
        return null;
    }
}
