package org.pangratz.netbeans.couchapp.actions;

import java.awt.Component;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import org.pangratz.netbeans.couchapp.ICouchAppUtil.CouchDbServer;

public class PushCouchAppPanel extends javax.swing.JPanel {

    private static class CouchDbServerRenderer extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList jlist, Object o, int i, boolean bln, boolean bln1) {
            if (o != null) {
                CouchDbServer server = (CouchDbServer) o;
                String name = server.getName();
                String url = server.getServer();
                String value = String.format("%s - %s", name, url);
                return super.getListCellRendererComponent(jlist, value, i, bln, bln1);
            }
            return super.getListCellRendererComponent(jlist, o, i, bln, bln1);
        }
    }

    private final ComboBoxModel couchDbServerModel;
    private final LinkedList<CouchDbServer> servers;

    /** Creates new form PushCouchAppPanel */
    public PushCouchAppPanel() {
        this(null);
    }

    private ComboBoxModel getCouchDbServerModel() {
        return couchDbServerModel;
    }

    public PushCouchAppPanel(List<CouchDbServer> servers) {
        super();
        
        this.servers = new LinkedList<CouchDbServer>();
        if (servers != null) {
            this.servers.addAll(servers);
        }
        couchDbServerModel = new DefaultComboBoxModel(this.servers.toArray());

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choicesButtonGroup = new javax.swing.ButtonGroup();
        predefinedCouchDbInstance = new javax.swing.JRadioButton();
        predefinedCouchDbInstancesComboBox = new javax.swing.JComboBox();
        newCouchDbInstance = new javax.swing.JRadioButton();
        newCouchDbLocationTextField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();

        choicesButtonGroup.add(predefinedCouchDbInstance);
        predefinedCouchDbInstance.setSelected(true);
        predefinedCouchDbInstance.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.predefinedCouchDbInstance.text")); // NOI18N

        predefinedCouchDbInstancesComboBox.setModel(getCouchDbServerModel());
        predefinedCouchDbInstancesComboBox.setRenderer(new CouchDbServerRenderer());

        choicesButtonGroup.add(newCouchDbInstance);
        newCouchDbInstance.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.newCouchDbInstance.text")); // NOI18N

        newCouchDbLocationTextField.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.newCouchDbLocationTextField.text")); // NOI18N

        messageLabel.setText(org.openide.util.NbBundle.getMessage(PushCouchAppPanel.class, "PushCouchAppPanel.messageLabel.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(predefinedCouchDbInstancesComboBox, 0, 345, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(messageLabel)
                        .addContainerGap())
                    .add(predefinedCouchDbInstance)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(29, 29, 29)
                                .add(newCouchDbLocationTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                            .add(newCouchDbInstance))
                        .add(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(messageLabel)
                .add(18, 18, 18)
                .add(predefinedCouchDbInstance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(predefinedCouchDbInstancesComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(newCouchDbInstance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(newCouchDbLocationTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup choicesButtonGroup;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JRadioButton newCouchDbInstance;
    private javax.swing.JTextField newCouchDbLocationTextField;
    private javax.swing.JRadioButton predefinedCouchDbInstance;
    private javax.swing.JComboBox predefinedCouchDbInstancesComboBox;
    // End of variables declaration//GEN-END:variables

    public String getChosenCouchDbUrl() {
        if (predefinedCouchDbInstance.isSelected()) {
            Object selectedItem = predefinedCouchDbInstancesComboBox.getSelectedItem();
            if (selectedItem != null) {
                CouchDbServer server = (CouchDbServer) selectedItem;
                return server.getServer();
            }
        } else if (newCouchDbInstance.isSelected()) {
            return newCouchDbLocationTextField.getText();
        }
        return null;
    }
}
